### ISSUE TITLE
Add link to file bug on the elementary home page

### ISSUE THREAD

**Issue by reubenfirmin** [elementary/mvp#989] opened 2016-01-16 16:46 UTC
If you don't want people filing bugs here, please include a reference to filing bugs on your home page.

**Comment by lewisgoddard** [comment] 2016-01-16 16:51
I think https://bugs.launchpad.net/elementaryos/+filebug should be on our support page under "file a bug", or maybe a link to the bug filing guide on the elementary OS StackExchange.

**Comment by danrabbit** [comment] 2016-01-16 18:39
I'm gonna say this is a duplicate of #968. It can be difficult for people to distinguish between something that should be filed as a bug and something that should be asked as a support question. I think we need to make sure people are guided to the correct venue.

I'm of the opinion that we shouldn't provide raw links to the bug tracker in user-focused spaces and I don't think the "support" section is appropriate for the bug tracker. We don't want to see *more* (yes more) reports with How/What/Where questions.

**Closed** 2016-03-17 17:29 UTC
Labels: Needs Design
