### ISSUE TITLE
Some bugs on website

### ISSUE THREAD

**Issue by RoyHabbort** [elementary/mvp#779] opened 2015-08-01 20:39 UTC
Hello. I'm faced some bugs on website elementary.io

First: Don' access to page
http://shot.qip.ru/00LtnB-61q1ISSOX/

Second: i'm pay 1$ and website was stoping.
Not download, not error. Only grey wrapper, when i click "download" button
http://shot.qip.ru/00LtnB-51q1ISSOY/
http://shot.qip.ru/00LtnB-61q1ISSOZ/

My country Russia. My browser Chrome. 

ps. if delete subdomain "beta", all working. But google make link on site with subdomain. I'm think that need take redirect.

**Comment by lewisgoddard** [comment] 2015-08-01 21:53
You should _not_ be on the beta subdomain. Could you tell me how you got there?

**Comment by fabianthoma** [comment] 2015-08-02 10:55
I get the beta subdomain if I enter `elementary os beta`, so yeah we need to add a robots file there

**Comment by aleksandar-todorovic** [comment] 2015-08-02 11:03
Definitely relevant issue: #780 

I think one of them should definitely be closed.

**Comment by RoyHabbort** [comment] 2015-08-02 15:54
http://shot.qip.ru/00LtnB-51q1ISSPa/
it's "elementary os freya download"

**Comment by lewisgoddard** [comment] 2015-08-02 17:31
Maybe that's a result of translation being available for that language on beta but not master, regardless, this is definitely a duplicate of #780.

**Closed by lewisgoddard** 2015-08-02 17:31 UTC
