### ISSUE TITLE
No Polish glyphs in Google Fonts

### ISSUE THREAD

**Issue by renegat59** [elementary/mvp#895] opened 2015-10-27 12:16 UTC
Polish glyphs like "łóśżźć" are not rendered proerly in the website. 
To solve it you should add subset=latin-ext to the google font declaration.

**Comment by aleksandar-todorovic** [comment] 2015-10-27 13:41
Duplicate of #411

**Comment by KeitIG** [comment] 2015-10-27 14:29
I'd say soluce of #411, not a duplicate

**Comment by lewisgoddard** [comment] 2015-10-27 21:42
We've previously marked all these kinds of reports as duplicates, seeing as adding that flag will automatically fix all fonts it can. Unfortunately, there's never been a consensus if `latin-ext` is enough.

**Closed** 2015-10-27 22:06 UTC
Labels: Status: Duplicate
