### ISSUE TITLE
Bad spacing on spanish version of Custom donation button

### ISSUE THREAD

**Issue by desiderantes** [elementary/mvp#687] opened 2015-06-04 17:42 UTC
As you can see in this screenshot, there is some overlap between the $ and the translation "Personalizar"

![Pic](https://cloud.githubusercontent.com/assets/1703429/7990487/f72325cc-0ab6-11e5-87d3-1b871555266c.PNG)

**Comment by lewisgoddard** [comment] 2015-06-04 17:47
This issue is a partial duplicate of #371 (also #652) and can be tracked there.

**Closed by lewisgoddard** 2015-06-04 17:47 UTC
