### ISSUE TITLE
Add bitcoin option to General Funding

### ISSUE THREAD

**Issue by jezekee** [elementary/mvp#978] opened 2016-01-07 15:19 UTC
Please add a Bitcoin button in the General Funding section on the [Get Involved page](https://elementary.io/get-involved), perhaps above the Paypal button (depends on which funding option is financially preferable).

If I have the option to pay using BTC when downloading but choose $0, it would be best if this option remains open should I choose to pay/donate later on. The way of doing so by going through the download button seems awkward.

Also, if the [stripe code](https://stripe.com/docs/guides/bitcoin) allows it, an option to pay with the email being optional would also be appreciated.

Similar to issue #624.

**Comment by danrabbit** [comment] 2016-01-09 00:13
Since Stripe does handle Bitcoin, I'm closing this as a duplicate of #624

**Closed by danrabbit** 2016-01-09 00:13 UTC
