### ISSUE TITLE
Font which is being used for headers is not good for multilingual sites

### ISSUE THREAD

**Issue by tomulin** [elementary/mvp#796] opened 2015-08-20 19:31 UTC
The font - Raleway, which is being used for headers (linked from google fonts) doesn't support extended latin. It's not a functional issue, it's rather visual. I'm sure that languages (czech, slovak and many more) which use diacritics are also affected.
![link](https://cloud.githubusercontent.com/assets/1255345/9393458/56814f8c-4782-11e5-85c5-0d593879b54e.png)

**Comment by lewisgoddard** [comment] 2015-08-20 19:34
Unfortunately, this is a duplicate of an existing issue, #411

**Closed by lewisgoddard** 2015-08-20 19:34 UTC
