### ISSUE TITLE
some of the "getting started" docs are out of date

### ISSUE THREAD

**Issue by laptag** [elementary/mvp#1146] opened 2016-05-07 06:37 UTC
I will update this with more things that I find. So far, all that I have found is that the cmake information is out of date and no longer works.

 - cmake

**Comment by lewisgoddard** [comment] 2016-05-07 10:26
Is it possible this is a duplicate of #1014 ?

**Comment by lewisgoddard** [comment] 2016-05-12 21:21
Unless you have something else to add here, this is a duplicate.

**Closed by lewisgoddard** 2016-05-12 21:21 UTC
Labels: Status: Duplicate
