### ISSUE TITLE
User should be able to zoom in

### ISSUE THREAD

**Issue by cybre** [elementary/mvp#280] opened 2015-01-29 11:36 UTC
You should not forbid users from zooming in. Just set the initial scale to 1.0 and let the user zoom in. It's generally a bad practice and should not be done.

**Comment by cassidyjames** [comment] 2015-01-29 17:14
I agree. Disabling zoom was issue #99 and was intended to fix mobile Safari's stupid behavior of automatically zooming in to input fields.

I believe the mobile Safari issue should be filed as its own bug and we should re-enable zooming, but I'll wait for feedback from the team before marking this as confirmed.

@danrabbit et al?

**Comment by danrabbit** [comment] 2015-01-29 17:22
I'd prefer if we could find a solution to the mobile safari issue before re-enabling zooming. The more important question for me is, why must you zoom? The website is already designed to fit your display. So from my perspective we're introducing a bug in exchange for a feature that isn't needed.

**Comment by cybre** [comment] 2015-01-29 17:27
You can set the font size of the inputs to 16px but I'm not sure that's
acceptable. (Not tested, found on google)

**Comment by cassidyjames** [comment] 2015-01-29 17:30
@danrabbit as I mentioned before, Safari will force the zooming if the text-size in inputs is below 16px. I played in the inspector and setting .button to 16px for mobile seems just fine.

Here are a few discussions as to why you wouldn't want to disable zooming:

http://www.mobify.com/blog/the-right-to-zoom/

http://ux.stackexchange.com/questions/37511/should-users-be-able-to-zoom-in-a-responsive-webdesign

http://jkg3.com/Journal/don-t-disable-pinch-to-zoom

One of the most interesting points was that people might want to see a picture in more detail or more accurately select text.

**Comment by danrabbit** [comment] 2015-01-29 19:55
Yeah if setting the size to 16px fixes it, I'm cool with that solution. The situation I want to avoid is where someone doesn't intentionally zoom in and then all the sudden they are zoomed in and our site looks broken.

**Closed** 2015-04-07 19:30 UTC
Labels: Critical, Needs Fixing
