### ISSUE TITLE
Layout problem on Spanish version of get-involved

### ISSUE THREAD

**Issue by Rybun** [elementary/mvp#374] opened 2015-02-09 18:26 UTC
On get-involved page, at the Spanish version, the links are out of the browser box:

![dev web](https://cloud.githubusercontent.com/assets/10455799/6111844/13a136ec-b08c-11e4-8060-4dc54cf36a87.jpg)

**Comment by danrabbit** [comment] 2015-02-09 18:28
This is a duplicate of #363

**Closed by danrabbit** 2015-02-09 18:28 UTC
