### ISSUE TITLE
Bad alignment when using Spanish translation

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/mvp#482] opened 2015-04-11 18:21 UTC
First in http://elementary.io/es/ (personalized amount button):

![captura de pantalla de 2015-04-11 15 16 58](https://cloud.githubusercontent.com/assets/6054951/7102681/44e55ea2-e05e-11e4-8616-0b8d8320ac66.png)

Second http://elementary.io/es/get-involved#web-development (open issues button):

![captura de pantalla de 2015-04-11 15 19 21](https://cloud.githubusercontent.com/assets/6054951/7102679/32a167fe-e05e-11e4-8e28-7d1d9848de33.png)

**Comment by lewisgoddard** [comment] 2015-04-11 18:45
Closing as a duplicate of #330

**Closed by lewisgoddard** 2015-04-11 18:45 UTC
