### ISSUE TITLE
Find an alternative to Satisfy font

### ISSUE THREAD

**Issue by aleksandar-todorovic** [elementary/mvp#782] opened 2015-08-03 22:39 UTC
Currently, the `<q>` tag uses the Satisfy font exclusively. However, Satisfy does not support some non-standard Latin characters (like `č`, `ć`, `š` and `ž`), which makes the quotes used in `/get-involved` weird when they're translated to some languages. Here's an example of a `/bs/` translation:

![screenshot from 2015-08-04 00 31 22](https://cloud.githubusercontent.com/assets/4890548/9049244/2d678408-3a40-11e5-853f-ab9ef6f07faf.png)

Plus it does not support the Cyrillic characters at all.

Unfortunately, I can't think of any handwriting font available on Google Fonts which could be a viable alternative.

**Comment by lewisgoddard** [comment] 2015-08-03 22:45
This is a duplicate of #411

**Closed** 2015-08-03 22:45 UTC
Labels: Duplicate
