### ISSUE TITLE
Cache-Control Headers

### ISSUE THREAD

**Issue by davidak** [elementary/mvp#328] opened 2015-01-31 17:00 UTC
let the browser cache static content like images, js, etc

for nginx:
```
location ~*  \.(jpg|jpeg|png|gif|ico|css|js)$ {
   expires 365d;
}
```

deactivate for development ;)

**Comment by lewisgoddard** [comment] 2015-05-07 16:19
With Cloudflare enabled, I'm not sure this is entirely necessary.

**Comment by lewisgoddard** [comment] 2015-06-20 21:55
This has become a duplicate of #648, which has a fix merged, but not implemented server-side yet.

**Closed by lewisgoddard** 2015-06-20 21:55 UTC
Labels: Duplicate
