### ISSUE TITLE
Get Involved chart is not updated

### ISSUE THREAD

**Issue by ggobbe** [elementary/mvp#1185] opened 2016-06-15 08:01 UTC
### Expected behavior

When accessing the Get Involved page, I expect the chart data to display the data in the chart.json file generated by chart.php.

### Actual behavior

If I have already visited the page in the last few days, it does not refresh the chart data, instead it uses a cached version of chart.json to display the chart on the Get Involved page.

### Steps to reproduce the behavior

1. Open the Get Involved page on day 1
2. Wait a few days and ensure that backend/chart.php has been triggered (I verified with another browser).
3. Open the Get Involved page on day 2 with the same browser as the one used on step 1
4. Look at the chart, it hasn't changed whilst if you open it with another browser that hasn't cached the chart.json file, it will display the latest version of the data.

### System information

- **Operating system**: any
- **Operating system version**: any
- **Browser**: any
- **Browser version**: any
- **Enabled Browser Extensions**: none

**Comment by lewisgoddard** [comment] 2016-06-15 11:50
This is a duplicate of #1131

**Closed** 2016-07-08 22:41 UTC
Labels: Status: Duplicate
