### ISSUE TITLE
No fallback font or included web font for Raleway

### ISSUE THREAD

**Issue by theRealPadster** [elementary/mvp#1249] opened 2016-08-08 19:23 UTC
### Expected behavior

The header font should be Raleway, or at least a sans-serif font. 

### Actual behavior

The header font was a generic serif font, and did not match the rest of the page at all. 

### Steps to reproduce the behavior

1. Open https://elementary.io/ on a system without Raleway (such as Windows)
2. Observer the level one headers like "Meet Our Apps"

### System information

- **Operating system**: Windows 7 x86_64
- **Operating system version**: 7 x86_64
- **Browser**: Google Chrome 52
- **Browser version**: 52
- **Enabled Browser Extensions**: Ublock Origin, Reddit New Comments Highlighter, Pomodoro Timer

**Comment by btkostner** [comment] 2016-08-08 19:38
We recently pushed a change to the server where we host the web font instead of using Google fonts. The style sheet is not updated yet due to cloud flare cache. Should be fixed soon hopefully

**Comment by btkostner** [comment] 2016-08-08 20:24
If you clear your cache you should see expected behavior now. Can you please confirm?

**Comment by theRealPadster** [comment] 2016-08-08 20:40
Yep, works now :)

**Closed** 2016-08-08 20:51 UTC
