### ISSUE TITLE
Sharing a quote in Twitter does not work for localized sites

### ISSUE THREAD

**Issue by Fitoschido** [elementary/mvp#558] opened 2015-04-20 02:13 UTC
1. Visit https://elementary.io/es/get-involved
2. Click on a quote, e.g., Federico Fellini's
3. Twitter will load the untranslated quote instead of the Spanish version.

**Comment by lewisgoddard** [comment] 2015-04-20 07:48
Thank you for the report, but unfortunately this is a duplicate of issue #412
You can view progress and responses there.

**Closed by lewisgoddard** 2015-04-20 07:48 UTC
Labels: duplicate
