### ISSUE TITLE
Cursive font doesn't include Latin Extended symbols

### ISSUE THREAD

**Issue by stannumman** [elementary/mvp#500] opened 2015-04-12 20:50 UTC
The font used for quotes on the "Get involved" page doesn't include letters like Č, Š, Ě, Ř, Ž, Ů, and perhaps others, making certain quotes look funky.
![Elementary website in Czech](https://cloud.githubusercontent.com/assets/2665210/7107441/0836f39a-e166-11e4-9e87-caf37f4ea2d6.png)

**Comment by lewisgoddard** [comment] 2015-04-12 21:23
This is being closed as it is a duplicate of #411Quotes font doesn't support non-latin languages

**Closed by lewisgoddard** 2015-04-12 21:23 UTC

**Comment by stannumman** [comment] 2015-04-13 07:21
Could you widen the scope of the bug, then? Czech does use the Latin alphabet.
