### ISSUE TITLE
Please provide a free download button

### ISSUE THREAD

**Issue by jonas2515** [elementary/mvp#358] opened 2015-02-07 14:10 UTC
I know developement of an OS is very expensive and I understand the devs wanting to get some reward for their hard work.
But I think it looks dubious to users of open source software when you don't show them a download button and I know many people coming from windows, who wanted elementary but left the website after they saw it's not free to download. Of course you can download it for free, but if the user doesn't know about this (and maybe also doesn't know about free software), he will leave the official website and maybe try to get it another way (maybe via a third party website) or just give up.

I think you should add a 0$ or a free button to the downloading menu and maybe focus it by default.

**Comment by lewisgoddard** [comment] 2015-02-07 14:26
Duplicate of #342

**Closed** 2015-02-07 14:27 UTC
Labels: duplicate
