### ISSUE TITLE
"Custom" payment button does not respect the width of the label

### ISSUE THREAD

**Issue by TicTac7x** [elementary/mvp#572] opened 2015-04-22 14:20 UTC
On the image you can see that the $ sign is on the top of the "Custom" button label, because it is too long and the width of the box is fixed.

![payment](https://cloud.githubusercontent.com/assets/7373586/7276625/9457f856-e913-11e4-8f31-e8cd11cffe06.png)

**Comment by lewisgoddard** [comment] 2015-04-22 14:55
This is a partial duplicate of #371 which documents several issues with the custom input/button.

**Closed by lewisgoddard** 2015-04-22 14:55 UTC
