### ISSUE TITLE
Create extensive "about" page

### ISSUE THREAD

**Issue by embik** [elementary/mvp#977] opened 2016-01-07 08:29 UTC
There is very little information about the technical details of elementary OS on elementary.io - While our primary target audience is not the "technical" user, I'd prefer to have an extensive list of technical details (formulated in a friendly way) delivered by *us*. This could be packaged in a nice and clean page, illustrated with logos and stuff like that.

A few ideas for sections on that page:

- Ubuntu, Debian and the relationship of elementary OS to them
- the Linux kernel
- the GNU project
- GNOME and its relationship to elementary OS / Pantheon

**Comment by danrabbit** [comment] 2016-01-07 08:32
Duplicate of #382

**Closed by danrabbit** 2016-01-07 08:32 UTC
