### ISSUE TITLE
Open Sans Local on Windows lacks some character sets.

### ISSUE THREAD

**Issue by tengwar** [elementary/mvp#544] opened 2015-04-18 12:42 UTC
Opens sans fonts used on homepage don't contain some characters, so Arial gets used instead. And it looks like Google webfonts version has the possibility to include those character sets. Windows 8.1, Firefox 37.0.1

Example:
![font_bug](https://cloud.githubusercontent.com/assets/7026772/7215451/ef08325e-e5d8-11e4-9f3a-83c5af3e6c89.png)

**Comment by emersion** [comment] 2015-04-18 12:52
Which language are you using? (I need it in order to reproduce)

**Comment by tengwar** [comment] 2015-04-18 13:02
Polish.

**Comment by emersion** [comment] 2015-04-18 13:09
Cannot reproduce on Archlinux

![screenshot from 2015-04-18 15-06-22](https://cloud.githubusercontent.com/assets/506932/7215523/4cad0864-e5dc-11e4-8201-5add03d8a021.png)

**Comment by tengwar** [comment] 2015-04-18 13:16
I guess on Arch system Open Sans is used as a fallback. Firefox tells me that here it uses Arial as a fallback.

**Comment by lewisgoddard** [comment] 2015-04-18 17:39
We're already inlcuding the web font: `https://fonts.googleapis.com/css?family=Raleway:100|Open+Sans:300,400,600|Droid+Sans+Mono`

**Comment by tengwar** [comment] 2015-04-19 19:34
@lewisgoddard Yes, but please take a look at https://developers.google.com/fonts/docs/getting_started#Subsets

**Comment by lewisgoddard** [comment] 2015-05-07 16:26
I'm going to mark this as a duplicate of #411 since that was filed first, hopefully we can get this sorted there.

**Comment by tengwar** [comment] 2015-12-17 22:51
Still not fixed. See https://github.com/elementary/mvp/issues/411#issuecomment-165582363

**Comment by lewisgoddard** [comment] 2015-12-17 23:53
I am re-opening this ticket to track Open Sans in Polish on certain systems only. I can confirm that this cannot be reproduced in elementary.

**Comment by fitojb** [comment] 2015-12-18 18:00
Of course you cannot reproduce in elementary because the Open Sans font is installed locally there. This issue only concerns the subsetted version that browsers download when that font is not installed.

**Comment by KeitIG** [comment] 2015-12-19 14:21
I'll test that issue on Windows tonight.

**Comment by lewisgoddard** [comment] 2015-12-20 16:45
I've tested on Windows 10, and Chrome doesn't do it but Firefox and IE do. A webfont link might work, but not if we allow local fallback (probably). I'll take a look into issues that don't affect Chrome.

**Closed** 2016-01-05 22:25 UTC
Labels: Status: In Progress
