### ISSUE TITLE
softly slide to sections using JS instead of reloading the website

### ISSUE THREAD

**Issue by davidak** [elementary/mvp#237] opened 2015-01-27 22:20 UTC
i use this to scroll up, that can also be implemented on the bottom of long sites.

```
<script type="text/javascript">
// scroll up button appears after moving down
$(window).scroll(function(){
        if ($(this).scrollTop() > 100) {
            $('.scrollup').fadeIn();
        } else {
            $('.scrollup').fadeOut();
        }
});

// by clicking the button, the site scrolls to top
$('.scrollup').click(function(){
    $("html, body").animate({ scrollTop: 0 }, 600);
    return false;
});

</script>
```

**Comment by danrabbit** [comment] 2015-01-27 22:24
This is a duplicate of #209

**Closed by danrabbit** 2015-01-27 22:24 UTC
