### ISSUE TITLE
Cyrillic fonts support

### ISSUE THREAD

**Issue by png2378** [elementary/mvp#747] opened 2015-07-21 15:27 UTC
Lack of support for cyrillic fonts make the site look very bad.

![](http://i.imgur.com/qcVpVFm.png)

![](http://i.imgur.com/SKwvoI1.png)

Open Sans and Droid Sans have support for the cyrillic on the Google Fonts. 

Raleway does not have support for the cyrillic, but there is [Raleway 3.0](http://www.impallari.com/projects/update/100) with its support. 

Satisfy doesn't have support for the Cyrillic, it maybe replaced by another.

**Comment by lewisgoddard** [comment] 2015-07-21 17:18
This issue is a duplicate of #411, and should be tracked there.

**Closed** 2015-07-21 17:18 UTC
Labels: Duplicate
