### ISSUE TITLE
Support page with answers

### ISSUE THREAD

**Issue by ventouris** [elementary/mvp#357] opened 2015-02-07 12:13 UTC
Will the Q&A page be implemented on the new website? http://elementaryos.org/answers

If not, do the developers support the creation of a dedicated Stack Exchange site? http://area51.stackexchange.com/proposals/82707/elementary-os

**Comment by danrabbit** [comment] 2015-02-07 16:59
I think for now we're going to try using Launchpad Answers. But if 
Stack Exchange turns out to be a much more vibrant community, I don't 
think anyone would have a problem switching to that instead.

**Comment by ventouris** [comment] 2015-02-07 17:10
Great. Thank you for your answer. The reason I asked you is because I took the initiative to start the site in SE and there was a lot of discussion about it in Reddit and in Google+ about it. If it is better to use Q&A in elementary OS site, Reddit or Google+ instead of Stack Exchange.

**Comment by cassidyjames** [comment] 2015-02-08 03:23
Closing as there's no real action item here, and it's kind of a dupe of #264

**Closed by cassidyjames** 2015-02-08 03:23 UTC
