### ISSUE TITLE
Bad alignment of 'Personalize' payment button in spanish

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/mvp#652] opened 2015-05-12 22:04 UTC
Self descriptive image:

![captura de pantalla de 2015-05-12 19 03 34](https://cloud.githubusercontent.com/assets/6054951/7599586/bcab8874-f8d9-11e4-923e-e0642140905c.png)

**Comment by lewisgoddard** [comment] 2015-05-12 22:15
This is a duplicate of one of the issues outlined in #371

**Closed** 2015-05-12 22:16 UTC
Labels: Duplicate
