### ISSUE TITLE
Moving slider over to css

### ISSUE THREAD

**Issue by btkostner** [elementary/mvp#653] opened 2015-05-12 22:52 UTC
Moving the slider over to css should help with animations, and layout problems. Right now, from what I can tell, it's mostly javascript with some interaction with the css. Javascript would still be required to control what content is being shown, but all animations should be hardware accelerated to give it a nice buttery smooth animation.

**Comment by danrabbit** [comment] 2015-05-14 19:58
Closing this as a dupe of #663 because Cass can't read

**Closed by danrabbit** 2015-05-14 19:58 UTC
Labels: Wishlist
